### ISSUE TITLE
Any chance for Free Flight mode ?

### ISSUE THREAD

**Issue by ALIENQuake** [tremwil/CatalystNoclipInjected#1]
Hi,
very nice project! But I would really like to explore bottom of the city etc. Any chance for Free Flight mode ?  Like this: https://www.youtube.com/watch?v=KfGEcyAYN9o Or anything which will prevent dead falling/animation and allow you just to land on the streets?

P.S. What API for Mirror's Edge: Catalyst can possibly do?

**Comment by tremwil** [comment]
Thank you for your request. If you wish to be able to "land" on the street, you can use my CatalystNoclipInjected project, as it is much more stable than than this one. Note that it wont remove the death barriers, so you might not be able to go EVERYWHERE. However, I heard that the app just doesn't work for some people. If it is the case for you, please open an issue on the other project so I can fix it. As for my API, it is good if you want to make a quick program / trainer for the game but it's not been updated in a while. I don't know if I will continue to work on it.

**Comment by ALIENQuake** [comment]
Hi, many thanks for you reply. I'm grateful for you work because not many people like this game and the chances for any kind of tools were lite to none. Maybe the github issues are not the best place to discuss but it was the only contact way which I could find :) I will ask other questions in separate issues.
