### ISSUE TITLE
Disable dead barriers 

### ISSUE THREAD

**Issue by ALIENQuake** [tremwil/CatalystNoclipInjected#2]
Forget about API but may I ask about possibility to disable dead barriers or put the payer directly below them to skip them and land on the floor? I'm aware that Denuvo/Game engine might make such task impossible/horrendous so any kind of answer from you will be greatly appreciated and accepted.

**Comment by tremwil** [comment]
Sorry, but my knowledge in game hacking/modding is far from great and I have no Idea how to disable death barriers. However, teleporting under them is easy (or you could just fly by them in RT mode) and often not needed since they are almost inexistant in the game.

**Comment by ALIENQuake** [comment]
@tremwil There is a mod which will do what I want: https://www.nexusmods.com/mirrorsedgecatalyst/mods/31
