### ISSUE TITLE
RT Noclip not working at all

### ISSUE THREAD

**Issue by ALIENQuake** [tremwil/CatalystNoclipInjected#3]
Hi again,

unless I'm wrong about RT mode, it doesn't work at my PC:

OS: Windows 10 15019
GFX: MSI GTX 1070
MirrorsEdgeCatalyst.exe: 1.0.3.47248

I'm pressing F1 and nothing happens, I can't fly into air. Also increasing speed doesn't have any effect because I'm still running normally at the floor.

I can run debbug version etc, prvide some info, even run VS but maybe before that, could you please make vide/gif/gfy about how F1 RT mode look at you PC?

**Comment by tremwil** [comment]
Hi, thank you for your report. Firstly, have you pressed the "Inject DLL" button after opening the game? If you did and got no error messages, please check if the Dll was correctly injected using Process Explorer or some other tool. Since it works perfectly for me on all my machines, I am unable to test this myself.

**Comment by tremwil** [comment]
If the DLL has been injected properly, you might want to kill yourself in the game once. The position pointers only work every two deaths.

**Comment by ALIENQuake** [comment]
Well, this is how my processes looks like: http://image.prntscr.com/image/05dd06ae77af47d0a7842f89d351685e.png
Not seing NoclipInjectedDll.dll is bad sign?

**Comment by tremwil** [comment]
Since Github issues arent the best places to exchange information rapidly, please join the Catalyst discord https://discord.gg/MkSKd in the Dev chatroom channel. It will be faster to fix your problem from there.

**Comment by WinkelCode** [comment]
I am experiencing the same issue, Freeze works, any noclip movement doesn't.

The old version works as expected except the non-working GUI (only visible for a couple frames sometimes when tabbing out), the same GUI issue is also present here,
