### ISSUE TITLE
CatalystNoclipInjected and just CatalystNoclip camera movement not working

### ISSUE THREAD

**Issue by pyciko** [tremwil/CatalystNoclipInjected#6]
The title is pretty straightforward. 
Both old Noclip and new NoclipInjected aren't working fine for me. I'm able to run the game, I'm able to switch between RT and FT modes, but whenever I try to move the camera around, nothing happens. Another thing I noticed: old Noclip at least shows its UI in the game, new one doesn't even show it.

Some stats:
Everything is running with admin elevation, Windows 10 LTSC and 20H2 (tried under both), Russian layout installed (I tried uninstalling it and running noclip again, still not working), Steam and Origin versions (tried both)

**Comment by pyciko** [comment]
UPD: found a fix on one of the Discord servers.
It suggests placing 2 DLLs in the game folder. It works!
But still, you should probably mention this fix in Readme.md or something...

**Comment by tremwil** [comment]
Thanks for the info! I don't play this game or support this tool anymore, but I'll gladly update the readme with your fix. Could you specify which DLLs you placed in the game files?

**Comment by pyciko** [comment]
Here they are 
https://gofile.io/d/mumY4y

**Comment by tremwil** [comment]
Thanks! I'll include that zip file in the readme.
